### ISSUE TITLE
ImportError: cannot import name 'closer' from 'gym.utils'

### ISSUE THREAD

**Issue by hishamunniyankal** [nphamilton/stl-gym#1]
I wanted to try stl-gym on my PC, but I could not find any clear instructions on how to install and run it. I tried to install the tool, but I encountered this error when I tried to run the example:
```
Traceback (most recent call last):
  File "/home/user/stl-gym/stlgym/stlgym.py", line 8, in <module>
    from gym.utils import closer, seeding
ImportError: cannot import name 'closer' from 'gym.utils' (/usr/local/lib/python3.10/dist-packages/gym-0.26.2-py3.10.egg/gym/utils/__init__.py)
```
I am using Ubuntu 22.04.2 LTS in WSL and Python 3.10. Can you please help me fix this issue?

**Comment by nphamilton** [comment]
Sorry. I always meant to write up the installation instructions but haven't had the time. One issue you will likely face is this library requires the Python version be >=3.6 and <3.9 so you'll need to start a conda environment with a more appropriate version. With that, running the following instructions in the terminal should get everything setup properly. Let me know if it doesn't work.

```bash
git clone --recursive https://github.com/nphamilton/stl-gym.git
cd stl-gym/rtamt/
pip install -e .
cd ..
pip install -e .
```
